# Generated by Django 4.2.7 on 2023-11-15 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=256)),
                ('urgently', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('optional', models.BooleanField(default=False)),
                ('entertainments', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
